import streamlit as st
from chain import run_chain

st.set_page_config(page_title="Northwind Data Assistant", layout="wide")

st.title("Northwind Data Assistant")
st.caption("Powered by phi3 + Cube.js semantic layer — fully local, no cloud")

# sample questions in sidebar
st.sidebar.header("Try These Questions")
samples = [
    "What are the top 5 countries by total revenue?",
    "How many orders do we have in total?",
    "Which product category has the highest average price?",
    "How many customers do we have per country?",
    "Who is the highest paid employee per department?",
    "Which products are out of stock?",
    "What is the total freight cost by country?",
]
for q in samples:
    if st.sidebar.button(q, use_container_width=True):
        st.session_state.pending_question = q

# chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# render chat history
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.write(msg["content"])
        if msg.get("cube_query"):
            with st.expander("Cube.js query generated by LLM"):
                st.json(msg["cube_query"])
        if msg.get("raw_data"):
            with st.expander("Raw data from Cube.js"):
                st.json(msg["raw_data"])

# handle sidebar button click
question = None
if "pending_question" in st.session_state:
    question = st.session_state.pop("pending_question")

# handle chat input
chat_input = st.chat_input("Ask a question about the data...")
if chat_input:
    question = chat_input

if question:
    # show user message
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.write(question)

    # run chain and show response
    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            result = run_chain(question)

        if "error" in result:
            st.error(result["error"])
            st.session_state.messages.append({
                "role": "assistant",
                "content": result["error"]
            })
        else:
            st.write(result["answer"])
            with st.expander("Cube.js query generated by LLM"):
                st.json(result["cube_query"])
            with st.expander("Raw data from Cube.js"):
                st.json(result["raw_data"])

            st.session_state.messages.append({
                "role": "assistant",
                "content": result["answer"],
                "cube_query": result["cube_query"],
                "raw_data": result["raw_data"]
            })
