import streamlit as st
import json
from chain import generate_cube_query, execute_and_answer, _is_data_question

st.set_page_config(page_title="Northwind Data Assistant", layout="wide")

st.title("Northwind Data Assistant")
st.caption("Powered by phi3 + Cube.js semantic layer — fully local, no cloud")

# sample questions in sidebar
st.sidebar.header("Try These Questions")
samples = [
    "What are the top 5 countries by total revenue?",
    "How many orders do we have in total?",
    "Which product category has the highest average price?",
    "How many customers do we have per country?",
    "Who is the highest paid employee per department?",
    "Which products are out of stock?",
    "What is the total freight cost by country?",
]
for q in samples:
    if st.sidebar.button(q, use_container_width=True):
        st.session_state.pending_question = q

# session state init
if "messages" not in st.session_state:
    st.session_state.messages = []
if "pending_query" not in st.session_state:
    st.session_state.pending_query = None  # holds {question, cube_query} awaiting confirmation

# render chat history
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.write(msg["content"])
        if msg.get("cube_query"):
            with st.expander("Cube.js query generated by LLM"):
                st.json(msg["cube_query"])
        if msg.get("raw_data"):
            with st.expander("Raw data from Cube.js"):
                st.json(msg["raw_data"])

# ── confirmation step ──────────────────────────────────────────────────────────
if st.session_state.pending_query:
    pq = st.session_state.pending_query
    st.info("**Review the query before executing:**")
    edited_query = st.text_area(
        "Cube.js query (edit if needed):",
        value=json.dumps(pq["cube_query"], indent=2),
        height=200
    )
    col1, col2 = st.columns(2)
    with col1:
        if st.button("Run this query", type="primary", use_container_width=True):
            try:
                cube_query = json.loads(edited_query)
            except json.JSONDecodeError:
                st.error("Invalid JSON — please fix the query above.")
                st.stop()

            with st.spinner("Querying Cube.js..."):
                result = execute_and_answer(pq["question"], cube_query)

            st.session_state.pending_query = None

            if "error" in result:
                st.session_state.messages.append({"role": "assistant", "content": result["error"]})
            else:
                st.session_state.messages.append({
                    "role": "assistant",
                    "content": result["answer"],
                    "cube_query": cube_query,
                    "raw_data": result["raw_data"]
                })
            st.rerun()

    with col2:
        if st.button("Cancel", use_container_width=True):
            st.session_state.pending_query = None
            st.rerun()
    st.stop()

# ── new question input ─────────────────────────────────────────────────────────
question = None
if "pending_question" in st.session_state:
    question = st.session_state.pop("pending_question")

chat_input = st.chat_input("Ask a question about the data...")
if chat_input:
    question = chat_input

if question:
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.write(question)

    if not _is_data_question(question):
        msg = "I can only answer questions about orders, products, customers, employees, revenue, and inventory."
        st.session_state.messages.append({"role": "assistant", "content": msg})
        st.rerun()

    with st.chat_message("assistant"):
        with st.spinner("Generating query..."):
            result = generate_cube_query(question)

        if "error" in result:
            st.error(result["error"])
            st.session_state.messages.append({"role": "assistant", "content": result["error"]})
        else:
            st.write("Here's the query I generated. Review and confirm to run it:")
            st.json(result["cube_query"])
            st.session_state.pending_query = {
                "question": question,
                "cube_query": result["cube_query"]
            }
            st.rerun()
